### ISSUE TITLE
An error during inference: AttributeError: 'Generator' object has no attribute 'remove_weight_norm'

### ISSUE THREAD

**Issue by egorsmkv** [hcy71o/AutoVocoder#2]
I am getting an error during inference:

```
Initializing Inference Process..
{'num_gpus': 0, 'batch_size': 32, 'learning_rate': 0.0002, 'adam_b1': 0.8, 'adam_b2': 0.99, 'lr_decay': 0.999, 'seed': 1234, 'n_blocks': 11, 'latent_dim': 256, 'latent_dropout': 0.1, 'dec_istft_input': 'cartesian', 'segment_size': 8192, 'num_mels': 80, 'n_fft': 1024, 'hop_size': 256, 'win_size': 1024, 'sampling_rate': 22050, 'fmin': 0, 'fmax': 8000, 'fmax_for_loss': None, 'num_workers': 4, 'dist_config': {'dist_backend': 'nccl', 'dist_url': 'tcp://localhost:54321', 'world_size': 1}}
Loading 'cp_autovocoder/g_00010000'
Complete.
Traceback (most recent call last):
  File "inference_file.py", line 88, in <module>
    main()
  File "inference_file.py", line 84, in main
    inference(a)
  File "inference_file.py", line 44, in inference
    generator.remove_weight_norm()
  File "/home/yehor/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Generator' object has no attribute 'remove_weight_norm'
```

**Comment by egorsmkv** [comment]
I figured out how to make inference after reading the code in train.py and its part where validation is going. I can now do inference over a file using an encoder and generator checkpoints. But it would be better to have the offiial inference file.

**Comment by egorsmkv** [comment]
@hcy71o can I close the issue?

**Comment by hcy71o** [comment]
Sorry for the late response. I'll add the inference code for future work :)

**Comment by egorsmkv** [comment]
Thanks Sent from my iPhoneOn 19 Dec 2022, at 21:29, Hyungchan Yoon ***@***.***> wrote:﻿
Sorry for the late response. I'll add the inference code for future work :)
